"""Public engine API contracts."""

from engine.api.action_dispatch import (
    ActionDispatcher,
    DirectActionHandler,
    PrefixedActionHandler,
    create_action_dispatcher,
)
from engine.api.ai import (
    Agent,
    Blackboard,
    DecisionContext,
    best_action,
    combine_weighted_scores,
    create_blackboard,
    create_functional_agent,
    normalize_scores,
)
from engine.api.app_port import EngineAppPort
from engine.api.assets import AssetHandle, AssetRegistry, create_asset_registry
from engine.api.commands import Command, CommandMap, create_command_map
from engine.api.context import RuntimeContext, create_runtime_context
from engine.api.debug import (
    DebugLoadedSession,
    DebugSessionBundle,
    discover_debug_sessions,
    export_crash_bundle,
    export_replay_session,
    export_profiling_snapshot,
    get_diagnostics_snapshot,
    get_metrics_snapshot,
    get_profiling_snapshot,
    get_replay_manifest,
    get_replay_snapshot,
    load_debug_session,
    validate_replay_snapshot,
)
from engine.api.dialogs import DialogOpenSpec, open_dialog, resolve_confirm_button_id
from engine.api.events import EventBus, Subscription, create_event_bus
from engine.api.flow import (
    FlowContext,
    FlowMachine,
    FlowProgram,
    FlowTransition,
    create_flow_machine,
    create_flow_program,
)
from engine.api.game_module import GameModule, HostControl, HostFrameContext
from engine.api.gameplay import (
    GameplaySystem,
    StateSnapshot,
    StateStore,
    SystemSpec,
    UpdateLoop,
    create_state_store,
    create_update_loop,
)
from engine.api.hosted_runtime import HostedRuntimeConfig, run_pygfx_hosted_runtime
from engine.api.input_events import KeyEvent, PointerEvent, WheelEvent
from engine.api.interaction_modes import (
    InteractionMode,
    InteractionModeMachine,
    create_interaction_mode_machine,
)
from engine.api.logging import EngineLoggingConfig, LoggerPort, configure_logging, get_logger
from engine.api.module_graph import ModuleGraph, ModuleNode, RuntimeModule, create_module_graph
from engine.api.render import RenderAPI
from engine.api.screens import ScreenLayer, ScreenStack, create_screen_stack
from engine.api.ui_framework import UIFramework, create_ui_framework
from engine.api.ui_primitives import (
    Button,
    CellCoord,
    GridLayout,
    ModalInputState,
    ModalKeyRoute,
    ModalPointerRoute,
    NonModalKeyRoute,
    PromptInteractionOutcome,
    PromptState,
    PromptView,
    Rect,
    ScrollOutcome,
    apply_wheel_scroll,
    can_scroll_list_down,
    can_scroll_with_wheel,
    clamp_scroll,
    close_prompt,
    handle_prompt_button,
    handle_prompt_char,
    handle_prompt_key,
    map_key_name,
    open_prompt,
    resolve_pointer_button,
    route_modal_key_event,
    route_modal_pointer_event,
    route_non_modal_key_event,
    sync_prompt,
    visible_slice,
)
from engine.api.ui_projection import ButtonSpec, project_buttons

__all__ = [
    "ActionDispatcher",
    "Agent",
    "AssetHandle",
    "AssetRegistry",
    "Blackboard",
    "Command",
    "CommandMap",
    "DecisionContext",
    "DebugLoadedSession",
    "DebugSessionBundle",
    "DirectActionHandler",
    "DialogOpenSpec",
    "EngineAppPort",
    "EventBus",
    "FlowContext",
    "FlowMachine",
    "FlowProgram",
    "FlowTransition",
    "GameModule",
    "GameplaySystem",
    "GridLayout",
    "HostControl",
    "HostFrameContext",
    "HostedRuntimeConfig",
    "InteractionMode",
    "InteractionModeMachine",
    "EngineLoggingConfig",
    "LoggerPort",
    "ModuleGraph",
    "ModuleNode",
    "PointerEvent",
    "KeyEvent",
    "WheelEvent",
    "Button",
    "ButtonSpec",
    "CellCoord",
    "ModalInputState",
    "ModalKeyRoute",
    "ModalPointerRoute",
    "NonModalKeyRoute",
    "PromptInteractionOutcome",
    "PromptState",
    "PromptView",
    "Rect",
    "ScrollOutcome",
    "RenderAPI",
    "RuntimeContext",
    "RuntimeModule",
    "ScreenLayer",
    "ScreenStack",
    "StateSnapshot",
    "StateStore",
    "Subscription",
    "SystemSpec",
    "UIFramework",
    "UpdateLoop",
    "best_action",
    "combine_weighted_scores",
    "create_action_dispatcher",
    "create_asset_registry",
    "create_blackboard",
    "create_command_map",
    "create_event_bus",
    "create_functional_agent",
    "create_flow_machine",
    "create_flow_program",
    "create_interaction_mode_machine",
    "configure_logging",
    "get_logger",
    "create_ui_framework",
    "discover_debug_sessions",
    "export_crash_bundle",
    "export_replay_session",
    "export_profiling_snapshot",
    "get_diagnostics_snapshot",
    "get_metrics_snapshot",
    "get_profiling_snapshot",
    "get_replay_manifest",
    "get_replay_snapshot",
    "load_debug_session",
    "normalize_scores",
    "validate_replay_snapshot",
    "run_pygfx_hosted_runtime",
    "create_module_graph",
    "create_runtime_context",
    "create_screen_stack",
    "create_state_store",
    "create_update_loop",
    "PrefixedActionHandler",
    "open_dialog",
    "project_buttons",
    "apply_wheel_scroll",
    "can_scroll_list_down",
    "can_scroll_with_wheel",
    "clamp_scroll",
    "close_prompt",
    "handle_prompt_button",
    "handle_prompt_char",
    "handle_prompt_key",
    "map_key_name",
    "open_prompt",
    "resolve_pointer_button",
    "route_modal_key_event",
    "route_modal_pointer_event",
    "route_non_modal_key_event",
    "resolve_confirm_button_id",
    "sync_prompt",
    "visible_slice",
]
