"""Public engine API contracts."""

from engine.api.action_dispatch import (
    ActionDispatcher,
    DirectActionHandler,
    PrefixedActionHandler,
)
from engine.api.ai import (
    Agent,
    Blackboard,
    DecisionContext,
    best_action,
    combine_weighted_scores,
    create_blackboard,
    create_functional_agent,
    normalize_scores,
)
from engine.api.app_port import EngineAppPort
from engine.api.assets import AssetHandle, AssetRegistry, create_asset_registry
from engine.api.commands import Command, CommandMap
from engine.api.composition import EngineModule
from engine.api.context import RuntimeContext
from engine.api.debug import (
    DebugLoadedSession,
    DebugSessionBundle,
    discover_debug_sessions,
    export_crash_bundle,
    export_profiling_snapshot,
    export_replay_session,
    get_diagnostics_snapshot,
    get_metrics_snapshot,
    get_profiling_snapshot,
    get_replay_manifest,
    get_replay_snapshot,
    load_debug_session,
    validate_replay_snapshot,
)
from engine.api.dialogs import DialogOpenSpec, open_dialog, resolve_confirm_button_id
from engine.api.events import EventBus, Subscription
from engine.api.flow import (
    FlowContext,
    FlowMachine,
    FlowProgram,
    FlowTransition,
)
from engine.api.game_module import GameModule, HostControl, HostFrameContext
from engine.api.gameplay import (
    GameplaySystem,
    StateSnapshot,
    StateStore,
    SystemSpec,
    UpdateLoop,
)
from engine.api.hosted_runtime import HostedRuntimeConfig
from engine.api.input_snapshot import (
    ActionSnapshot,
    ControllerSnapshot,
    InputSnapshot,
    KeyboardSnapshot,
    MouseSnapshot,
    create_empty_input_snapshot,
)
from engine.api.input_events import KeyEvent, PointerEvent, WheelEvent
from engine.api.interaction_modes import (
    InteractionMode,
    InteractionModeMachine,
)
from engine.api.logging import EngineLoggingConfig, LoggerPort
from engine.api.module_graph import ModuleGraph, ModuleNode, RuntimeModule
from engine.api.render import RenderAPI
from engine.api.render_snapshot import (
    IDENTITY_MAT4,
    Mat4,
    RenderCommand,
    RenderPassSnapshot,
    RenderSnapshot,
    Vec3,
    create_render_snapshot,
)
from engine.api.screens import ScreenLayer, ScreenStack
from engine.api.ui_framework import UIFramework
from engine.api.ui_style import (
    DEFAULT_UI_STYLE_TOKENS,
    UIStyleTokens,
    draw_gradient_rect,
    draw_rounded_rect,
    draw_shadow_rect,
    draw_stroke_rect,
)
from engine.api.ui_primitives import (
    Button,
    CellCoord,
    GridLayout,
    ModalInputState,
    ModalKeyRoute,
    ModalPointerRoute,
    NonModalKeyRoute,
    PromptInteractionOutcome,
    PromptState,
    PromptView,
    Rect,
    ScrollOutcome,
    TextOverflowPolicy,
    apply_text_overflow,
    apply_wheel_scroll,
    can_scroll_list_down,
    can_scroll_with_wheel,
    clamp_child_rect_to_parent,
    clamp_scroll,
    clip_text,
    close_prompt,
    fit_text_to_rect,
    handle_prompt_button,
    handle_prompt_char,
    handle_prompt_key,
    map_key_name,
    open_prompt,
    resolve_pointer_button,
    route_modal_key_event,
    route_modal_pointer_event,
    route_non_modal_key_event,
    sync_prompt,
    parent_rect_from_children,
    truncate_text,
    visible_slice,
)
from engine.api.ui_projection import ButtonSpec, TextFitSpec, project_buttons, project_text_fit
from engine.api.window import (
    SurfaceHandle,
    WindowCloseEvent,
    WindowEvent,
    WindowFocusEvent,
    WindowMinimizeEvent,
    WindowPort,
    WindowResizeEvent,
)

__all__ = [
    "ActionDispatcher",
    "Agent",
    "AssetHandle",
    "AssetRegistry",
    "Blackboard",
    "Command",
    "CommandMap",
    "EngineModule",
    "DecisionContext",
    "DebugLoadedSession",
    "DebugSessionBundle",
    "DirectActionHandler",
    "DialogOpenSpec",
    "EngineAppPort",
    "EventBus",
    "FlowContext",
    "FlowMachine",
    "FlowProgram",
    "FlowTransition",
    "GameModule",
    "GameplaySystem",
    "GridLayout",
    "HostControl",
    "HostFrameContext",
    "HostedRuntimeConfig",
    "InputSnapshot",
    "InteractionMode",
    "InteractionModeMachine",
    "KeyboardSnapshot",
    "EngineLoggingConfig",
    "LoggerPort",
    "Mat4",
    "ModuleGraph",
    "ModuleNode",
    "MouseSnapshot",
    "PointerEvent",
    "KeyEvent",
    "RenderCommand",
    "RenderPassSnapshot",
    "RenderSnapshot",
    "SurfaceHandle",
    "Vec3",
    "WheelEvent",
    "WindowCloseEvent",
    "WindowEvent",
    "WindowFocusEvent",
    "WindowMinimizeEvent",
    "WindowPort",
    "WindowResizeEvent",
    "ActionSnapshot",
    "Button",
    "ButtonSpec",
    "TextFitSpec",
    "CellCoord",
    "TextOverflowPolicy",
    "ControllerSnapshot",
    "ModalInputState",
    "ModalKeyRoute",
    "ModalPointerRoute",
    "NonModalKeyRoute",
    "PromptInteractionOutcome",
    "PromptState",
    "PromptView",
    "Rect",
    "ScrollOutcome",
    "RenderAPI",
    "RuntimeContext",
    "RuntimeModule",
    "ScreenLayer",
    "ScreenStack",
    "StateSnapshot",
    "StateStore",
    "Subscription",
    "SystemSpec",
    "UIFramework",
    "UpdateLoop",
    "best_action",
    "combine_weighted_scores",
    "create_asset_registry",
    "create_blackboard",
    "create_functional_agent",
    "create_empty_input_snapshot",
    "create_render_snapshot",
    "UIStyleTokens",
    "DEFAULT_UI_STYLE_TOKENS",
    "draw_rounded_rect",
    "draw_stroke_rect",
    "draw_gradient_rect",
    "draw_shadow_rect",
    "load_debug_session",
    "normalize_scores",
    "validate_replay_snapshot",
    "PrefixedActionHandler",
    "open_dialog",
    "project_buttons",
    "project_text_fit",
    "IDENTITY_MAT4",
    "apply_wheel_scroll",
    "apply_text_overflow",
    "can_scroll_list_down",
    "can_scroll_with_wheel",
    "clamp_child_rect_to_parent",
    "clamp_scroll",
    "clip_text",
    "close_prompt",
    "fit_text_to_rect",
    "handle_prompt_button",
    "handle_prompt_char",
    "handle_prompt_key",
    "map_key_name",
    "open_prompt",
    "resolve_pointer_button",
    "route_modal_key_event",
    "route_modal_pointer_event",
    "route_non_modal_key_event",
    "resolve_confirm_button_id",
    "parent_rect_from_children",
    "sync_prompt",
    "truncate_text",
    "visible_slice",
]
